version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/ArtNetSharp/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "nuget"
    directory: "/ArtNetSharpTests/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5