name: Build & Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
        
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet-version: [ '7.0', '8.0', '9.0']
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.2.0
      with:
          dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore -p:TargetFramework=net${{ matrix.dotnet-version }}
    - name: Build
      run: dotnet build -p:TargetFramework=net${{ matrix.dotnet-version }} --configuration Release --no-restore
    - name: Test
      run: dotnet test --framework net${{ matrix.dotnet-version }} --collect:"XPlat Code Coverage" --no-restore --verbosity detailed --logger trx --results-directory "TestResults-${{ matrix.os }} ${{ matrix.dotnet-version }}"
    - name: Upload a Build Artifact
      if: ${{ failure() || success() }}
      uses: actions/upload-artifact@v4.6.0
      with:
        name: ${{ matrix.os }} ${{ matrix.dotnet-version }}
        path: |
          ArtNetTests/bin/*/net${{ matrix.dotnet-version }}/log.txt
          TestResults-${{ matrix.os }} ${{ matrix.dotnet-version }}
          ArtNetSharp/bin/Release/net${{ matrix.dotnet-version }}/ArtNetSharp.dll
        retention-days: 2
      continue-on-error: true

