name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet-version: [ '6.0.x', '7.0.x', '8.0.x' ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal --logger trx --results-directory "TestResults-${{ matrix.os }} ${{ matrix.dotnet-version }}"
    # - name: Upload dotnet test results
    #   uses: actions/upload-artifact@v4.3.1
    #   with:
    #     name: TestResults-${{ matrix.os }} ${{ matrix.dotnet-version }}
    #     path: TestResults-${{ matrix.os }} ${{ matrix.dotnet-version }}
    #     retention-days: 30
    #     # Use always() to always run this step to publish test results when there are test failures
    #   continue-on-error: true
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: ${{ matrix.os }} ${{ matrix.dotnet-version }}
        path: |
          TestResults-${{ matrix.os }} ${{ matrix.dotnet-version }}
          ArtNetSharp/bin/Release/**/ArtNetSharp.dll
        retention-days: 2
      continue-on-error: true

