name: Publish Packages to nuget

on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: | 
            6.0.x
            7.0.x
            8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        path: ArtNetSharp/bin/Release/**/ArtNetSharp.dll
    - name: Publish ArtNetSharp
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: ArtNetSharp/ArtNetSharp.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          PACKAGE_NAME: ArtNetSharp
