name: Publish Packages to nuget

on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.2.0
      with:
          dotnet-version: | 
            7.0
            8.0
            9.0
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        path: ArtNetSharp/bin/Release/**/ArtNetSharp.dll
    - name: Create Nuget Package
      run: dotnet pack --configuration Release
    - name: Upload to Nuget.org
      run: dotnet nuget push ArtNetSharp/bin/Release/ArtNetSharp.*.nupkg --api-key ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json
